[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = False
warn_redundant_casts = False
warn_unused_configs = False
plugins = 
    mypy_django_plugin.plugin

[mypy.plugins.django-stubs]
django_settings_module = config.settings