# Generated by Django 6.0.2 on 2026-04-06 19:35

import api.model.evidencia
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pt_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoanalise',
            name='tipo_infracao',
        ),
        migrations.RenameField(
            model_name='evidencia',
            old_name='denucia',
            new_name='denuncia',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='password',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='codigo_legal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='descricao_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='sentido_direccao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resultadoanalise',
            name='caminho_ficheiro_processado',
            field=models.FileField(blank=True, null=True, upload_to='videos_processados/'),
        ),
        migrations.AddField(
            model_name='resultadoanalise',
            name='codigo_legal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resultadoanalise',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='caminho_ficheiro',
            field=models.FileField(upload_to=api.model.evidencia.upload_evidencia_path),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='data_captura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='TipoInfracao',
        ),
    ]
