# Generated by Django 6.0.2 on 2026-04-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_resultadoanalise_tipo_infracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='tipo_infracao',
            field=models.CharField(blank=True, choices=[('CONTRAMAO', 'contramao'), ('PARADO', 'parado'), ('VELOCIDADE', 'velocidade')], max_length=20, null=True),
        ),
    ]
