# Generated by Django 6.0.2 on 2026-04-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_denuncia_tipo_infracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='data_registo',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='numero',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
