# Generated by Django 6.0.2 on 2026-09-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_utilizador_data_registo_utilizador_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
