# Generated by Django 6.0.2 on 2026-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_denuncia_latitude_denuncia_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor_encriptado', models.TextField()),
                ('publica', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
