# Generated by Django 6.0.2 on 2026-09-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_configuracaoapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaJurisdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_via', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255)),
                ('geometria', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias_jurisdicao', to='api.admin')),
            ],
            options={
                'unique_together': {('admin', 'place_id')},
            },
        ),
    ]
