# Generated by Django 6.0.2 on 2026-09-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_viajurisdicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_acidente', to='api.admin'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_infracao',
            field=models.CharField(blank=True, choices=[('CONTRAMAO', 'contramao'), ('PARADO', 'parado'), ('VELOCIDADE', 'velocidade'), ('ACIDENTE', 'acidente')], max_length=20, null=True),
        ),
    ]
