# Generated by Django 6.0.2 on 2026-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_denuncia_admin_responsavel_utilizador_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
