# Generated by Django 6.0.2 on 2026-09-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_denuncia_atualizado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='fcm_token',
        ),
    ]
