# Generated by Django 6.0.2 on 2026-09-30 07:31

from django.db import migrations, models


def acidentes_existentes(apps, schema_editor):
    # Acidentes criados antes destes estados ficaram PENDENTE (e aparecia
    # "a processar" ao cidadão). Com posto -> ENCAMINHADA; com agente -> EM_ATENDIMENTO.
    Denuncia = apps.get_model("api", "Denuncia")
    acidentes = Denuncia.objects.filter(tipo_infracao="ACIDENTE", estado="PENDENTE")
    acidentes.filter(pt__isnull=False).update(estado="EM_ATENDIMENTO")
    acidentes.filter(pt__isnull=True, admin_responsavel__isnull=False).update(estado="ENCAMINHADA")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remover_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('VALIDADA', 'Validada'), ('REJEITADA', 'Rejeitada'), ('APROVADA', 'Aprovada'), ('ARQUIVADA', 'Arquivada'), ('ENCAMINHADA', 'Encaminhada ao posto'), ('EM_ATENDIMENTO', 'Agente designado')], default='PENDENTE', max_length=20),
        ),
        migrations.RunPython(acidentes_existentes, migrations.RunPython.noop),
    ]
