# Generated by Django 6.0.2 on 2026-09-30 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_estados_acidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DENUNCIA_RECEBIDA', 'Denúncia recebida'), ('ESTADO_ALTERADO', 'Estado da denúncia alterado'), ('NOVA_PARA_REVISAO', 'Nova denúncia para revisão'), ('ACIDENTE_REPORTADO', 'Acidente reportado'), ('AGENTE_DESIGNADO', 'Designado para acidente')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.CharField(max_length=500)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='api.denuncia')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['utilizador', 'lida'], name='api_notific_utiliza_2aff67_idx')],
            },
        ),
    ]
