# Generated by Django 6.0.2 on 2026-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('DENUNCIA_RECEBIDA', 'Denúncia recebida'), ('ESTADO_ALTERADO', 'Estado da denúncia alterado'), ('NOVA_PARA_REVISAO', 'Nova denúncia para revisão'), ('ACIDENTE_REPORTADO', 'Acidente reportado'), ('AGENTE_DESIGNADO', 'Designado para acidente'), ('ANALISE_FALHOU', 'Falha na análise do vídeo')], max_length=30),
        ),
    ]
