# Generated by Django 6.0.2 on 2026-09-30 08:54

import django.db.models.deletion
import hashlib

from django.db import migrations, models


def calcular_hashes(apps, schema_editor):
    # Só calcula a impressão digital dos ficheiros já existentes, para um
    # ficheiro antigo também não poder ser reenviado. Não mexe nas
    # denúncias repetidas que já existem.
    Evidencia = apps.get_model("api", "Evidencia")
    for e in Evidencia.objects.filter(hash_sha256__isnull=True):
        try:
            h = hashlib.sha256()
            with e.caminho_ficheiro.open("rb") as f:
                for bloco in iter(lambda: f.read(1024 * 1024), b""):
                    h.update(bloco)
            e.hash_sha256 = h.hexdigest()
            e.save(update_fields=["hash_sha256"])
        except Exception:
            pass  # ficheiro em falta no disco


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notificacao_analise_falhou'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='denuncia_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relacionadas', to='api.denuncia'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='hash_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.RunPython(calcular_hashes, migrations.RunPython.noop),
    ]
