# Generated by Django 6.0.2 on 2026-09-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_duplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='video_semelhante_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_semelhantes', to='api.denuncia'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('DENUNCIA_RECEBIDA', 'Denúncia recebida'), ('ESTADO_ALTERADO', 'Estado da denúncia alterado'), ('NOVA_PARA_REVISAO', 'Nova denúncia para revisão'), ('ACIDENTE_REPORTADO', 'Acidente reportado'), ('AGENTE_DESIGNADO', 'Designado para acidente'), ('ANALISE_FALHOU', 'Falha na análise do vídeo'), ('DENUNCIA_RELACIONADA', 'Denúncia relacionada')], max_length=30),
        ),
        migrations.CreateModel(
            name='AssinaturaFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BigIntegerField()),
                ('b0', models.IntegerField(db_index=True)),
                ('b1', models.IntegerField(db_index=True)),
                ('b2', models.IntegerField(db_index=True)),
                ('b3', models.IntegerField(db_index=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='api.evidencia')),
            ],
        ),
    ]
