# Generated by Django 6.0.2 on 2026-09-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_assinatura_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='localizacao_contraditoria',
            field=models.BooleanField(default=False),
        ),
    ]
