# Generated by Django 6.0.2 on 2026-09-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_localizacao_contraditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='decidido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='designado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
